# Generated by Django 5.0.3 on 2024-03-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoAddRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("upc", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(null=True)),
                ("message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManualAddRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("upc", models.CharField(max_length=20)),
                ("item_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(null=True)),
                ("message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
